using System;
using System.Collections.Generic;

#nullable disable

namespace amanatApi.Models
{
    public partial class ERP_EXT
    {
        public int ID { get; set; }
        public int ASSETID { get; set; }
        public string ASSETS_P1_1 { get; set; }
        public string ASSETS_P1_2 { get; set; }
        public string ASSETS_P1_3 { get; set; }
        public string ASSETS_P1_4 { get; set; }
        public string ASSETS_P1_5 { get; set; }
        public string ASSETS_P1_6 { get; set; }
        public string ASSETS_P1_7 { get; set; }
        public string ASSETS_P1_8 { get; set; }
        public string ASSETS_P1_9 { get; set; }
        public string ASSETS_P2_1 { get; set; }
        public string ASSETS_P2_2 { get; set; }
        public string ASSETS_P2_3 { get; set; }
        public string ASSETS_P2_4 { get; set; }
        public string ASSETS_P2_5 { get; set; }
        public string ASSETS_P2_6 { get; set; }
        public string ASSETS_P2_7 { get; set; }
        public string ASSETS_P2_8 { get; set; }
        public string ASSETS_P2_9 { get; set; }
        public string ASSETS_P3_1 { get; set; }
        public string ASSETS_P3_10 { get; set; }
        public string ASSETS_P3_11 { get; set; }
        public string ASSETS_P3_12 { get; set; }
        public string ASSETS_P3_13 { get; set; }
        public string ASSETS_P3_14 { get; set; }
        public string ASSETS_P3_15 { get; set; }
        public string ASSETS_P3_16 { get; set; }
        public string ASSETS_P3_17 { get; set; }
        public string ASSETS_P3_2 { get; set; }
        public string ASSETS_P3_3 { get; set; }
        public string ASSETS_P3_4 { get; set; }
        public string ASSETS_P3_5 { get; set; }
        public string ASSETS_P3_6 { get; set; }
        public string ASSETS_P3_7 { get; set; }
        public string ASSETS_P3_8 { get; set; }
        public string ASSETS_P3_9 { get; set; }
        public string ASSETS_P5_1 { get; set; }
        public string ASSETS_P5_2 { get; set; }
        public string ASSETS_P5_3 { get; set; }
        public string ASSETS_P5_4 { get; set; }
        public string ASSETS_P6_1 { get; set; }
        public string ASSETS_P6_2 { get; set; }
        public string ASSETS_P6_3 { get; set; }
        public string ASSETS_P6_4 { get; set; }
        public string ASSETS_P6_5 { get; set; }
        public string ASSETS_P6_6 { get; set; }
        public string ASSETS_P6_7 { get; set; }
        public string ASSETS_P7_1 { get; set; }
        public string ASSETS_P7_10 { get; set; }
        public string ASSETS_P7_11 { get; set; }
        public string ASSETS_P7_12 { get; set; }
        public string ASSETS_P7_13 { get; set; }
        public string ASSETS_P7_14 { get; set; }
        public string ASSETS_P7_15 { get; set; }
        public string ASSETS_P7_16 { get; set; }
        public string ASSETS_P7_2 { get; set; }
        public string ASSETS_P7_3 { get; set; }
        public string ASSETS_P7_4 { get; set; }
        public string ASSETS_P7_5 { get; set; }
        public string ASSETS_P7_6 { get; set; }
        public string ASSETS_P7_7 { get; set; }
        public string ASSETS_P7_8 { get; set; }
        public string ASSETS_P7_9 { get; set; }
        public string ASSETS_P8_1 { get; set; }
        public string ASSETS_P8_2 { get; set; }
        public string ASSETS_P8_3 { get; set; }
        public string ASSETS_P8_4 { get; set; }
        public string ASSETS_P9_1 { get; set; }
        public string ASSETS_P9_2 { get; set; }
        public string ASSETS_P9_3 { get; set; }
        public string ASSETS_P9_4 { get; set; }
        public string ASSETS_P9_5 { get; set; }
        public string ASSETS_P9_6 { get; set; }
        public string ASSETS_P10_1 { get; set; }
        public string ASSETS_P10_10 { get; set; }
        public string ASSETS_P10_11 { get; set; }
        public string ASSETS_P10_12 { get; set; }
        public string ASSETS_P10_2 { get; set; }
        public string ASSETS_P10_3 { get; set; }
        public string ASSETS_P10_4 { get; set; }
        public string ASSETS_P10_5 { get; set; }
        public string ASSETS_P10_6 { get; set; }
        public string ASSETS_P10_7 { get; set; }
        public string ASSETS_P10_8 { get; set; }
        public string ASSETS_P10_9 { get; set; }
        public string ASSETS_P11_1 { get; set; }
        public string ASSETS_P11_2 { get; set; }
        public string ASSETS_P11_3 { get; set; }
        public string ASSETS_P11_4 { get; set; }
        public string ASSETS_P11_5 { get; set; }
        public string ASSETS_P11_6 { get; set; }
        public string ASSETS_P11_7 { get; set; }
        public string ASSETS_P11_8 { get; set; }
        public string ASSETS_P11_9 { get; set; }
        public string ASSETS_P12_1 { get; set; }
        public string ASSETS_P12_2 { get; set; }
        public string ASSETS_P12_3 { get; set; }
        public string ASSETS_P12_4 { get; set; }
        public string ASSETS_P12_5 { get; set; }
        public string ASSETS_P12_6 { get; set; }
        public string ASSETS_P13_1 { get; set; }
        public string ASSETS_P13_2 { get; set; }
        public string ASSETS_P13_3 { get; set; }
        public string ASSETS_P13_4 { get; set; }
        public string ASSETS_P14_1 { get; set; }
        public string ASSETS_P14_2 { get; set; }
        public string ASSETS_P14_3 { get; set; }
        public string ASSETS_P14_4 { get; set; }
        public string ASSETS_P14_5 { get; set; }
        public string ASSETS_P14_6 { get; set; }
        public string ASSETS_P15_1 { get; set; }
        public string ASSETS_P15_10 { get; set; }
        public string ASSETS_P15_11 { get; set; }
        public string ASSETS_P15_12 { get; set; }
        public string ASSETS_P15_13 { get; set; }
        public string ASSETS_P15_14 { get; set; }
        public string ASSETS_P15_15 { get; set; }
        public string ASSETS_P15_16 { get; set; }
        public string ASSETS_P15_17 { get; set; }
        public string ASSETS_P15_18 { get; set; }
        public string ASSETS_P15_19 { get; set; }
        public string ASSETS_P15_2 { get; set; }
        public string ASSETS_P15_20 { get; set; }
        public string ASSETS_P15_3 { get; set; }
        public string ASSETS_P15_4 { get; set; }
        public string ASSETS_P15_5 { get; set; }
        public string ASSETS_P15_6 { get; set; }
        public string ASSETS_P15_7 { get; set; }
        public string ASSETS_P15_8 { get; set; }
        public string ASSETS_P15_9 { get; set; }

        public virtual ERP_ASSET ASSET { get; set; }
    }
}
