using System;
using System.Collections.Generic;

#nullable disable

namespace amanatApi.Models
{
    public partial class ERP_ASSET2
    {
        public int ID { get; set; }
        public string LABEL { get; set; }
        public string NAME { get; set; }
        public string SNBN { get; set; }
        public int? CODEID { get; set; }
        public string PN { get; set; }
        public string MODEL { get; set; }
        public int? BRAND { get; set; }
        public int ASSETTYPE { get; set; }
        public int? LABELTYPE { get; set; }
        public string OLDLABEL { get; set; }
        public string LATINNAME { get; set; }
        public int? COUNTRY { get; set; }
        public double? QUANTITY { get; set; }
        public int? QUANTITYUNIT { get; set; }
        public double? QUALITY { get; set; }
        public int? VALUETYPE { get; set; }
        public double? VALUE { get; set; }
        public int? CURRENCY { get; set; }
        public double? EXCHANGERATE { get; set; }
        public int? EARNINGTYPE { get; set; }
        public string OLDOWNER { get; set; }
        public double? BOOKVALUE { get; set; }
        public double? SAVEDAMOUNT { get; set; }
        public double? USEFULAGE { get; set; }
        public int? PRODATE { get; set; }
        public int? EXPDATE { get; set; }
        public DateTime? PRODATEG { get; set; }
        public DateTime? EXPDATEG { get; set; }
        public int? PURCHASEDATE { get; set; }
        public int? OPERATIONDATE { get; set; }
        public int? LETTERDATE { get; set; }
        public string LETTERNO { get; set; }
        public string LETTERSUBJECT { get; set; }
        public string SELLERNAME { get; set; }
        public string SELLERPHONE { get; set; }
        public string SELLERADDRESS { get; set; }
        public string WARANTY { get; set; }
        public int? WARANTYBEGINDATE { get; set; }
        public int? WARANTYENDDATE { get; set; }
        public string DESCRIPTION { get; set; }
        public int? RECEIVERID { get; set; }
        public int? KEEPINGLOCATIONID { get; set; }
        public int? ROOTLOCATION { get; set; }
        public int ISACTIVE { get; set; }
        public int? RECLOCATIONID { get; set; }
        public double REMAIN { get; set; }
        public int? CONDITION { get; set; }
        public int? CALCDATE { get; set; }
        public int? MAINOWNER { get; set; }
        public int? ID2 { get; set; }
        public int? PARENTID { get; set; }
        public int? EXTRACTFROMID { get; set; }
        public int? MAINPLAKFAREIID { get; set; }
        public int? PLAKASLITEMPLATEID { get; set; }
        public string TRACKINGNO { get; set; }
        public int? LASTPAPERITEMID { get; set; }
        public int? SHELFFROM { get; set; }
        public int? SHELFTO { get; set; }
        public int? EXITDATE { get; set; }
        public int? EXITREASON { get; set; }
        public string EXITTO { get; set; }
        public int? USAGE { get; set; }
        public string AMLAK_SABTI_ASLI { get; set; }
        public string AMLAK_SABTI_FAREI { get; set; }
        public string AMLAK_VARAGHE_MALEKIAT { get; set; }
        public string KHODRO_MOTOR { get; set; }
        public string KHODRO_SHASI { get; set; }
        public string KHODRO_ENTEZAMI { get; set; }
        public int? KHODRO_NOTYPE { get; set; }
        public string PHONE_NO { get; set; }
        public string AMLAK_POSTALCODE { get; set; }
        public int? CREATEDATE { get; set; }
        public int? EXIT_PAPERITEM { get; set; }
        public int? ROOTASSETID { get; set; }
        public int? MATERIAL { get; set; }
        public double? LENGTHX { get; set; }
        public double? DIAMETER { get; set; }
        public double? AREA { get; set; }
        public double? CAPACITY { get; set; }
        public double? WEIGHT { get; set; }
        public double? FORCE { get; set; }
        public double? PRESSURE { get; set; }
        public double? POWER { get; set; }
        public int? COLOR { get; set; }
        public double? COURSE { get; set; }
        public double? VOLTAGE { get; set; }
        public double? AMPER { get; set; }
        public double? RESISTANCE { get; set; }
        public int? RESISTANCEUNIT { get; set; }
        public int? AMPERUNIT { get; set; }
        public int? VOLTAGEUNIT { get; set; }
        public int? COURSEUNIT { get; set; }
        public int? POWERUNIT { get; set; }
        public int? PRESSUREUNIT { get; set; }
        public int? FORCEUNIT { get; set; }
        public int? WEIGHTUNIT { get; set; }
        public int? DIAMETERUNIT { get; set; }
        public int? LENGTHXUNIT { get; set; }
        public int? AREAUNIT { get; set; }
        public int? CAPACITYUNIT { get; set; }
        public double? ARZI { get; set; }
        public byte[] OLDID { get; set; }
        public double? REPAIR_TOTALCOST { get; set; }
        public int? ONPACKAGEID { get; set; }
        public int? OLDLBL { get; set; }
        public int? OLDPARENTID { get; set; }
        public int? OLDEXTID { get; set; }
        public int? OLDRID { get; set; }
        public int? OLDPID { get; set; }
        public double? COUNTER { get; set; }
        public int? NLABEL { get; set; }
        public int CREATOR { get; set; }
        public int? ONPAPERID { get; set; }
        public string OLDLID { get; set; }
        public string OLDCODE { get; set; }
        public int? KHODRO_NOTYPE2 { get; set; }
        public int? BRAND2 { get; set; }
        public int? MODELID { get; set; }
    }
}
