using System;
using System.Collections.Generic;

#nullable disable

namespace amanatApi.Models
{
    public partial class VIEW_PAPER
    {
        public int P_ID { get; set; }
        public int P_NO { get; set; }
        public string P_FULLNO { get; set; }
        public int? P_PAPERDATE { get; set; }
        public int ELAPSED { get; set; }
        public int P_CREATEDATE { get; set; }
        public int? P_PAPEREXPDATE { get; set; }
        public int P_PAPERTYPE { get; set; }
        public string P_PAPERTYPE_STR { get; set; }
        public int P_APPROVED { get; set; }
        public int P_ACTIVE { get; set; }
        public int P_DELETED { get; set; }
        public int P_ROOTLOCATION { get; set; }
        public string P_ROOT_TITLE { get; set; }
        public string P_ROOT_CODE { get; set; }
        public int? P_ROOTLOCATION2 { get; set; }
        public string P_ROOT2_TITLE { get; set; }
        public string P_ROOT2_CODE { get; set; }
        public int? P_SEN_LOCATION { get; set; }
        public string P_SEN_LOCATION_TITLE { get; set; }
        public string P_SEN_LOCATION_CODE { get; set; }
        public int? P_SEN_LOCATIONTYPE { get; set; }
        public string P_SEN_ROOTCODE { get; set; }
        public string P_SEN_ROOTTITLE { get; set; }
        public int? P_SEN_USER { get; set; }
        public string P_SEN_USER_PID { get; set; }
        public string P_SEN_USER_NAME { get; set; }
        public int? P_REC_LOCATION { get; set; }
        public string P_REC_LOCATION_TITLE { get; set; }
        public string P_REC_LOCATION_CODE { get; set; }
        public int? P_REC_LOCATIONTYPE { get; set; }
        public int? P_REC_USER { get; set; }
        public string P_REC_USER_PID { get; set; }
        public string P_REC_USER_NAME { get; set; }
        public int? P_SEN_RES_LOCATION { get; set; }
        public string P_SEN_RES_LOCATION_TITLE { get; set; }
        public string P_SEN_RES_LOCATION_CODE { get; set; }
        public int? P_SEN_RES_USER { get; set; }
        public string P_SEN_RES_PID { get; set; }
        public string P_SEN_RES_NAME { get; set; }
        public int? P_SEN_AMIN_LOCATION { get; set; }
        public string P_SEN_AMIN_LOCATION_TITLE { get; set; }
        public string P_SEN_AMIN_LOCATION_CODE { get; set; }
        public int? P_SEN_AMIN_USER { get; set; }
        public string P_SEN_AMIN_PID { get; set; }
        public string P_SEN_AMIN_NAME { get; set; }
        public int? P_SEN_HAMIN_LOCATION { get; set; }
        public string P_SEN_HAMIN_LOCATION_TITLE { get; set; }
        public string P_SEN_HAMIN_LOCATION_CODE { get; set; }
        public int? P_SEN_HAMIN_USER { get; set; }
        public string P_SEN_HAMIN_PID { get; set; }
        public string P_SEN_HAMIN_NAME { get; set; }
        public int? P_STOREKEEPERUSER { get; set; }
        public int? P_REC_AMIN_LOCATION { get; set; }
        public string P_REC_AMIN_LOCATION_TITLE { get; set; }
        public string P_REC_AMIN_LOCATION_CODE { get; set; }
        public int? P_REC_AMIN_USER { get; set; }
        public string P_REC_AMIN_PID { get; set; }
        public string P_REC_AMIN_NAME { get; set; }
        public int? P_REC_HAMIN_LOCATION { get; set; }
        public int? P_REC_HAMIN_LOCATION_TITLE { get; set; }
        public int? P_REC_HAMIN_LOCATION_CODE { get; set; }
        public int? P_REC_HAMIN_USER { get; set; }
        public int? P_REC_HAMIN_PID { get; set; }
        public int? P_REC_HAMIN_NAME { get; set; }
        public int? P_REC_RES_LOCATION { get; set; }
        public string P_REC_RES_LOCATION_TITLE { get; set; }
        public string P_REC_RES_LOCATION_CODE { get; set; }
        public int? P_REC_RES_USER { get; set; }
        public string P_REC_RES_PID { get; set; }
        public string P_REC_RES_NAME { get; set; }
        public int? P_TARGETLOCATION { get; set; }
        public string P_TARGETLOCATION_TITLE { get; set; }
        public string P_TARGETLOCATION_CODE { get; set; }
        public int? P_TARGETUSER { get; set; }
        public string P_TARGETUSER_PID { get; set; }
        public string P_TARGETUSER_NAME { get; set; }
        public int P_CREATOR { get; set; }
        public string P_CREATOR_PID { get; set; }
        public string P_CREATOR_NAME { get; set; }
        public string P_LICENCE_NO { get; set; }
        public int? P_LICENCE_DATE { get; set; }
        public string P_LICENCE_CREATOR { get; set; }
        public string P_LICENCE_IMAGE_URL { get; set; }
        public int? P_ORIGINALPAPERID { get; set; }
        public int P_PAPERYEAR { get; set; }
        public int? P_RESERVEDFORUNIT { get; set; }
        public string P_RESERVEDFORUNIT_TITLE { get; set; }
        public string P_RESERVEDFORUNIT_CODE { get; set; }
        public int? P_FKOPERTOR { get; set; }
        public int? P_FKOPERTOR_PID { get; set; }
        public int? P_FKOPERT_ORNAME { get; set; }
        public int? P_DEADLINE { get; set; }
        public string P_FKMACHINETYPE { get; set; }
        public int? P_MACHINETYPE_STR { get; set; }
        public int? P_FKMACHINE { get; set; }
        public int? P_MACHINE_STR { get; set; }
        public int? P_FKCOMPANY { get; set; }
        public string P_COMPANY_NAME { get; set; }
        public int? P_FKPRIORITY { get; set; }
        public string P_PRIORITY_STR { get; set; }
        public int? P_FKREQUESTUSER { get; set; }
        public string P_REQUESTUSER_PID { get; set; }
        public string P_REQUESTUSER_NAME { get; set; }
        public int? P_FKREQUESTLOCATION { get; set; }
        public string P_REQUESTLOCATION_TITLE { get; set; }
        public string P_REQUESTLOCATION_CODE { get; set; }
        public int? P_FKREQUEST { get; set; }
        public string P_REQUEST_FULLNO { get; set; }
        public int? P_REQUEST_SEN_USER_PID { get; set; }
        public int? P_REQUEST_SEN_USER_NAME { get; set; }
        public int? P_REQUEST_SEN_LOCATION_CODE { get; set; }
        public int? P_REQUEST_SEN_LOCATION_TITLE { get; set; }
        public int? P_REQUEST_PAPERDATE { get; set; }
        public string P_AWB { get; set; }
        public string P_INVOICE_NO { get; set; }
        public double? P_INVOICE_PRICE { get; set; }
        public double? P_INVOICE_DISCOUNT { get; set; }
        public double? P_INVOICE_TAX { get; set; }
        public double? P_INVOICE_FINALPRICE { get; set; }
        public double? P_TRANSPORTCOST { get; set; }
        public double? P_COST_ADDITIVE { get; set; }
        public int? P_TRANSPORTDATE { get; set; }
        public string P_TRANSPORTER { get; set; }
        public int? P_DELIVERYDATE { get; set; }
        public string P_QUOTATION { get; set; }
        public int? P_INVOICE_DATE { get; set; }
        public string P_DESCRIPTION { get; set; }
        public double? P_COST_SUBTRACTIVE { get; set; }
        public int? P_RECEIPTDATE { get; set; }
        public int? P_INVOICE_CURRENCY { get; set; }
        public string P_LICENCE_DESCRIPTION { get; set; }
        public int? P_KEEPING_LOCATION { get; set; }
        public string P_KEEPING_LOCATION_TITLE { get; set; }
        public string P_KEEPING_LOCATION_CODE { get; set; }
        public int? HOGHUGHI_USER { get; set; }
        public string HOGHUGHI_USER_PID { get; set; }
        public string HOGHUGHI_USER_NAME { get; set; }
        public int? HOGHUGHI_LOCATION { get; set; }
        public string HOGHUGHI_LOCATION_TITLE { get; set; }
        public string HOGHUGHI_LOCATION_CODE { get; set; }
        public int? KASR_COMPANY { get; set; }
        public string KASR_COMPANY_NAME { get; set; }
        public string KASR_RABETNAME { get; set; }
        public string KASR_PLAK_TAHVILI { get; set; }
        public double? KASR_SELL_VALUE { get; set; }
        public int? KASR_SELL_CURRENCY { get; set; }
        public string KASR_SELL_MOZAIEDE { get; set; }
        public int? KASR_SERGHAT_USERID { get; set; }
        public string KASR_SERGHAT_PID { get; set; }
        public string KASR_SERGHAT_NAME { get; set; }
        public double? KASR_SERGHAT_KARSHENASI { get; set; }
        public double? KASR_SERGHT_MANAVI { get; set; }
        public int? KASR_DEADLINE { get; set; }
        public int? KASR_RETURN_DATE { get; set; }
        public int KASR_REMAIN { get; set; }
        public int KASR_RETURNED { get; set; }
        public string KASR_RETURNED_STR { get; set; }
        public int EXIT_STATUS { get; set; }
        public string EXIT_STATUS_STR { get; set; }
        public int? KASR_DATE { get; set; }
        public string KASR_REASON_STR { get; set; }
        public int? KASR_REASON { get; set; }
        public int IS_CONTINUAL { get; set; }
        public int? REC_ANBARDAR_USER { get; set; }
        public string REC_ANBARDAR_USER_NAME { get; set; }
        public string REC_ANBARDAR_USER_PID { get; set; }
        public int? REC_ANBARDAR_LOCATION { get; set; }
        public string REC_ANBARDAR_LOCATION_TITLE { get; set; }
        public string REC_ANBARDAR_LOCATION_CODE { get; set; }
        public string SHOP { get; set; }
        public int? SHOPID { get; set; }
        public string SELLER { get; set; }
        public string SHOPADDRESS { get; set; }
        public string SHOPPHONE { get; set; }
        public int? MARJU_REASON { get; set; }
        public string MARJU_REASON_TITLE { get; set; }
        public int? RELATEDPAPER { get; set; }
        public string CACHEDKEY { get; set; }
        public int? FKMACHINE { get; set; }
        public long? MACHINE_LABEL { get; set; }
        public string MACHINE_NAME { get; set; }
        public int? CORRECTED { get; set; }
        public int? BUYFOR { get; set; }
        public string BUYFORCODE { get; set; }
        public string BUYFORTITLE { get; set; }
    }
}
