using System;
using System.Collections.Generic;

#nullable disable

namespace amanatApi.Models
{
    public partial class VIEW_PAPER_LIST
    {
        public int PI_ID { get; set; }
        public double PI_QUANTITY { get; set; }
        public float? PI_INIT_QTY { get; set; }
        public double PI_PRICE { get; set; }
        public double PI_TOTALPRICE { get; set; }
        public string PI_REASON { get; set; }
        public int? PI_RECID { get; set; }
        public string PI_REC_PID { get; set; }
        public string PI_REC_NAME { get; set; }
        public int? PI_RECLOCATIONID { get; set; }
        public string PI_RECLOCATION_TITLE { get; set; }
        public string PI_RECLOCATION_CODE { get; set; }
        public int? PI_SENDERID { get; set; }
        public string PI_SENDER_PID { get; set; }
        public string PI_SENDER_NAME { get; set; }
        public int? PI_SENDERLOCATIONID { get; set; }
        public string PI_SENDERLOCATION_TITLE { get; set; }
        public string PI_SENDERLOCATION_CODE { get; set; }
        public int? PI_SENDERROOTLOCATIONID { get; set; }
        public int? PI_QUANTITYUNIT { get; set; }
        public string PI_QUANTITYUNIT_STR { get; set; }
        public int? PI_REQUEST_FULLNO { get; set; }
        public int? PI_TEMP_DELIVERY_FULLNO { get; set; }
        public int? PI_CONDITION { get; set; }
        public string PI_CONDITION_STR { get; set; }
        public int? PI_TASK_STR { get; set; }
        public string PI_DESCRIPTION { get; set; }
        public int? PI_DELIVERYDATE { get; set; }
        public int? STATUS { get; set; }
        public int? STATUS_BY { get; set; }
        public string STATUS_BY_NAME { get; set; }
        public string STATUS_BY_PIDS { get; set; }
        public int? STATUS_DATE { get; set; }
        public string STATUS_DATE_F { get; set; }
        public string STATUS_STR { get; set; }
        public int ASSET_ID { get; set; }
        public string ASSET_LABEL { get; set; }
        public long? ASSET_NLABEL { get; set; }
        public string ASSET_NAME { get; set; }
        public string ASSET_SNBN { get; set; }
        public int? ASSET_CODEID { get; set; }
        public string ASSET_CODE { get; set; }
        public string ASSET_PN { get; set; }
        public string ASSET_MODEL { get; set; }
        public int? ASSET_BRAND { get; set; }
        public string ASSET_BRAND_STR { get; set; }
        public int ASSET_ASSETTYPE { get; set; }
        public string ASSET_ASSETTYPE_STR { get; set; }
        public string ASSET_LATINNAME { get; set; }
        public int? ASSET_COUNTRY { get; set; }
        public string ASSET_COUNTRY_STR { get; set; }
        public int? ASSET_VALUETYPE { get; set; }
        public string ASSET_VALUETYPE_STR { get; set; }
        public double? ASSET_VALUE { get; set; }
        public int? ASSET_CURRENCY { get; set; }
        public string ASSET_CURRENCY_STR { get; set; }
        public int? ASSET_EARNINGTYPE { get; set; }
        public string ASSET_EARNINGTYPE_STR { get; set; }
        public long? ASSET_PRODATE { get; set; }
        public long? ASSET_EXPDATE { get; set; }
        public long? ASSET_PURCHASEDATE { get; set; }
        public long? ASSET_OPERATIONDATE { get; set; }
        public long? ASSET_LETTERDATE { get; set; }
        public string ASSET_LETTERNO { get; set; }
        public string ASSET_LETTERSUBJECT { get; set; }
        public string ASSET_DESCRIPTION { get; set; }
        public int? ASSET_RECEIVERID { get; set; }
        public string ASSET_REC_PID { get; set; }
        public string ASSET_REC_NAME { get; set; }
        public int? ASSET_ROOTLOCATION { get; set; }
        public string ASSET_ROOT_CODE { get; set; }
        public string ASSET_ROOT_TITLE { get; set; }
        public int? ASSET_RECLOCATIONID { get; set; }
        public string ASSET_RECLOCATION_CODE { get; set; }
        public string ASSET_RECLOCATION_TITLE { get; set; }
        public int? ASSET_CONDITION { get; set; }
        public string ASSET_CONDITION_STR { get; set; }
        public int? ASSET_PARENTID { get; set; }
        public string ASSET_TRACKINGNO { get; set; }
        public int? ASSET_USAGE { get; set; }
        public string ASSET_USAGE_STR { get; set; }
        public string ASSET_SABTI_ASLI { get; set; }
        public string ASSET_SABTI_FAREI { get; set; }
        public string ASSET_VARAGHE_MALEKIAT { get; set; }
        public string ASSET_ENTEZAMI { get; set; }
        public string ASSET_MOTOR { get; set; }
        public string ASSET_SHASI { get; set; }
        public string ASSET_PHONE_NO { get; set; }
        public double ASSET_AVAILABLEQTY { get; set; }
        public int? ASSET_MATERIAL { get; set; }
        public int? ASSET_COLOR { get; set; }
        public string ASSET_COLOR_STR { get; set; }
        public double? ASSET_LENGTHX { get; set; }
        public double? ASSET_DIAMETER { get; set; }
        public double? ASSET_AREA { get; set; }
        public double? ASSET_CAPACITY { get; set; }
        public double? ASSET_WEIGHT { get; set; }
        public double? ASSET_FORCE { get; set; }
        public double? ASSET_PRESSURE { get; set; }
        public double? ASSET_POWER { get; set; }
        public double? ASSET_COURSE { get; set; }
        public double? ASSET_VOLTAGE { get; set; }
        public double? ASSET_AMPER { get; set; }
        public double? ASSET_RESISTANCE { get; set; }
        public int CODE_TYPE { get; set; }
        public double? ASSET_ARZI { get; set; }
        public int P_ID { get; set; }
        public int P_NO { get; set; }
        public string P_FULLNO { get; set; }
        public int? P_PAPERDATE { get; set; }
        public int ELAPSED { get; set; }
        public int P_CREATEDATE { get; set; }
        public int? P_PAPEREXPDATE { get; set; }
        public int P_PAPERTYPE { get; set; }
        public string P_PAPERTYPE_STR { get; set; }
        public int P_ACTIVE { get; set; }
        public int P_ROOTLOCATION { get; set; }
        public string P_ROOT_TITLE { get; set; }
        public string P_ROOT_CODE { get; set; }
        public int? P_ROOTLOCATION2 { get; set; }
        public string P_ROOT2_TITLE { get; set; }
        public string P_ROOT2_CODE { get; set; }
        public int? P_SEN_LOCATION { get; set; }
        public string P_SEN_LOCATION_TITLE { get; set; }
        public string P_SEN_LOCATION_CODE { get; set; }
        public int? P_SEN_USER { get; set; }
        public string P_SEN_USER_PID { get; set; }
        public string P_SEN_USER_NAME { get; set; }
        public int? P_REC_LOCATION { get; set; }
        public string P_REC_LOCATION_TITLE { get; set; }
        public string P_REC_LOCATION_CODE { get; set; }
        public int? P_REC_LOCATIONTYPE { get; set; }
        public int? P_REC_USER { get; set; }
        public string P_REC_USER_PID { get; set; }
        public string P_REC_USER_NAME { get; set; }
        public int? P_SEN_RES_USER { get; set; }
        public string P_SEN_RES_PID { get; set; }
        public string P_SEN_RES_NAME { get; set; }
        public int? P_SEN_AMIN_USER { get; set; }
        public string P_SEN_AMIN_PID { get; set; }
        public string P_SEN_AMIN_NAME { get; set; }
        public int? P_SEN_HAMIN_USER { get; set; }
        public string P_SEN_HAMIN_PID { get; set; }
        public string P_SEN_HAMIN_NAME { get; set; }
        public int? P_REC_AMIN_USER { get; set; }
        public string P_REC_AMIN_PID { get; set; }
        public string P_REC_AMIN_NAME { get; set; }
        public int? P_REC_HAMIN_USER { get; set; }
        public int? P_REC_HAMIN_PID { get; set; }
        public int? P_REC_HAMIN_NAME { get; set; }
        public int? P_REC_RES_USER { get; set; }
        public string P_REC_RES_PID { get; set; }
        public string P_REC_RES_NAME { get; set; }
        public int P_CREATOR { get; set; }
        public string P_CREATOR_PID { get; set; }
        public string P_CREATOR_NAME { get; set; }
        public string P_LICENCE_NO { get; set; }
        public int? P_LICENCE_DATE { get; set; }
        public string P_LICENCE_CREATOR { get; set; }
        public string P_LICENCE_DESCRIPTION { get; set; }
        public int? P_RESERVEDFORUNIT { get; set; }
        public string P_RESERVEDFORUNIT_TITLE { get; set; }
        public string P_RESERVEDFORUNIT_CODE { get; set; }
        public int? P_DEADLINE { get; set; }
        public int? P_FKPRIORITY { get; set; }
        public string P_PRIORITY_STR { get; set; }
        public string P_AWB { get; set; }
        public string P_INVOICE_NO { get; set; }
        public int? P_DELIVERYDATE { get; set; }
        public int? P_INVOICE_DATE { get; set; }
        public string P_DESCRIPTION { get; set; }
        public int? P_RECEIPTDATE { get; set; }
        public int? P_INVOICE_CURRENCY { get; set; }
        public int? HOGHUGHI_USER { get; set; }
        public string HOGHUGHI_USER_PID { get; set; }
        public string HOGHUGHI_USER_NAME { get; set; }
        public int? HOGHUGHI_LOCATION { get; set; }
        public string HOGHUGHI_LOCATION_TITLE { get; set; }
        public string HOGHUGHI_LOCATION_CODE { get; set; }
        public int? KASR_COMPANY { get; set; }
        public string KASR_COMPANY_NAME { get; set; }
        public string KASR_RABETNAME { get; set; }
        public string KASR_PLAK_TAHVILI { get; set; }
        public double? KASR_SELL_VALUE { get; set; }
        public int? KASR_SELL_CURRENCY { get; set; }
        public string KASR_SELL_MOZAIEDE { get; set; }
        public int? KASR_SERGHAT_USERID { get; set; }
        public string KASR_SERGHAT_PID { get; set; }
        public string KASR_SERGHAT_NAME { get; set; }
        public double? KASR_SERGHAT_KARSHENASI { get; set; }
        public double? KASR_SERGHT_MANAVI { get; set; }
        public int? KASR_DEADLINE { get; set; }
        public string KASR_DEADLINE_F { get; set; }
        public int KASR_REMAIN { get; set; }
        public int? KASR_RETURN_DATE { get; set; }
        public string KASR_RETURN_DATE_F { get; set; }
        public int KASR_RETURNED { get; set; }
        public int? KASR_REASON { get; set; }
        public string KASR_REASON_STR { get; set; }
        public int? KASR_DATE { get; set; }
        public int IS_CONTINUAL { get; set; }
        public int EXIT_STATUS { get; set; }
        public string EXIT_STATUS_STR { get; set; }
        public int REMAIN_STATUS { get; set; }
        public string SHOP { get; set; }
        public int? SHOPID { get; set; }
        public string SELLER { get; set; }
        public string SHOPADDRESS { get; set; }
        public string SHOPPHONE { get; set; }
        public int? MARJU_REASON { get; set; }
        public string MARJU_REASON_TITLE { get; set; }
        public int? RELATEDPAPER { get; set; }
        public int? FKMACHINE { get; set; }
        public long? MACHINE_LABEL { get; set; }
        public string MACHINE_NAME { get; set; }
        public string ASSET_QUANTITYUNIT_STR { get; set; }
    }
}
