using System;
using System.Collections.Generic;

#nullable disable

namespace amanatApi.Models
{
    public partial class VIEW_MELK
    {
        public int ASSET_ID { get; set; }
        public string ASSET_LABEL { get; set; }
        public string ASSET_NAME { get; set; }
        public long? ASSET_NLABEL { get; set; }
        public int ASSET_CODEID { get; set; }
        public string ASSET_CODE { get; set; }
        public string ASSET_OLDLABEL { get; set; }
        public int? ASSET_COUNTRY { get; set; }
        public string ASSET_COUNTRY_STR { get; set; }
        public double? ASSET_QUALITY { get; set; }
        public int? ASSET_VALUETYPE { get; set; }
        public string ASSET_VALUETYPE_STR { get; set; }
        public double? ASSET_VALUE { get; set; }
        public int ASSET_CURRENCY { get; set; }
        public string ASSET_CURRENCY_STR { get; set; }
        public double? ASSET_EXCHANGERATE { get; set; }
        public int? ASSET_EARNINGTYPE { get; set; }
        public string ASSET_EARNINGTYPE_STR { get; set; }
        public string ASSET_OLDOWNER { get; set; }
        public double? ASSET_BOOKVALUE { get; set; }
        public double? ASSET_SAVEDAMOUNT { get; set; }
        public double? ASSET_USEFULAGE { get; set; }
        public long ASSET_PURCHASEDATE { get; set; }
        public long ASSET_OPERATIONDATE { get; set; }
        public long? ASSET_LETTERDATE { get; set; }
        public string ASSET_LETTERNO { get; set; }
        public string ASSET_LETTERSUBJECT { get; set; }
        public string ASSET_SELLERNAME { get; set; }
        public string ASSET_SELLERPHONE { get; set; }
        public string ASSET_SELLERADDRESS { get; set; }
        public string ASSET_DESCRIPTION { get; set; }
        public int ASSET_RECEIVERID { get; set; }
        public string ASSET_REC_PID { get; set; }
        public string ASSET_REC_NAME { get; set; }
        public int ASSET_KEEPINGLOCATIONID { get; set; }
        public int ASSET_ROOTLOCATION { get; set; }
        public string ASSET_ROOT_CODE { get; set; }
        public string ASSET_ROOT_TITLE { get; set; }
        public int ASSET_RECLOCATIONID { get; set; }
        public string ASSET_RECLOCATION_CODE { get; set; }
        public string ASSET_RECLOCATION_TITLE { get; set; }
        public int RECLOCATION_TYPE { get; set; }
        public double ASSET_REMAIN { get; set; }
        public int? ASSET_CONDITION { get; set; }
        public string ASSET_CONDITION_STR { get; set; }
        public long? ASSET_CALCDATE { get; set; }
        public int? ASSET_MAINOWNER { get; set; }
        public int? ASSET_ID2 { get; set; }
        public string ASSET_TRACKINGNO { get; set; }
        public int? ASSET_LASTPAPERITEMID { get; set; }
        public long? ASSET_EXITDATE { get; set; }
        public int? ASSET_EXITREASON { get; set; }
        public string ASSET_EXITTO { get; set; }
        public int? ASSET_USAGE { get; set; }
        public string ASSET_POSTALCODE { get; set; }
        public string ASSET_SABTI_ASLI { get; set; }
        public string ASSET_SABTI_FAREI { get; set; }
        public string ASSET_VARAGHE_MALEKIAT { get; set; }
        public double RESERVEDQTY { get; set; }
        public double ASSET_AVAILABLEQTY { get; set; }
        public int IS_EXITED { get; set; }
        public int? EXIT_PAPERITEM { get; set; }
        public int? SANADNO { get; set; }
        public int? MAKHZAN_NO { get; set; }
        public int INOUTSTATUS { get; set; }
        public string INOUTSTATUS_STR { get; set; }
        public int? ID { get; set; }
        public int? COUNTRYID { get; set; }
        public string COUNTRY_TITLE { get; set; }
        public string STATE { get; set; }
        public string CITY { get; set; }
        public string MAFRUZ { get; set; }
        public int? N_GHETE { get; set; }
        public string HORUF { get; set; }
        public int? KARBARIID { get; set; }
        public string KARBARI_TITLE { get; set; }
        public string BAHREBARDAR { get; set; }
        public int? EGHRARNAMEID { get; set; }
        public string EGHRARNAME_TITLE { get; set; }
        public string MOSHAKHSAT { get; set; }
        public double? F_MASAHATKOL { get; set; }
        public double? F_ZIRBANA { get; set; }
        public int? PAYANKARID { get; set; }
        public string PAYANKAR_TITLE { get; set; }
        public int? SANADTEDAD { get; set; }
        public string VMALEKIAT { get; set; }
        public int? SANADVAZIATID { get; set; }
        public string SANADVAZIAT_TITLE { get; set; }
        public int? SANADTYPEID { get; set; }
        public string SANADTYPE_TITLE { get; set; }
        public int? MALEKIATTYPEID { get; set; }
        public string MALEKIATTYPE_TITLE { get; set; }
        public string MALEK { get; set; }
        public int? MALEKPID { get; set; }
        public string MALEK_PID { get; set; }
        public string MALEK_NAME { get; set; }
        public string MANTAGHE { get; set; }
        public string BAKHSHSABTI { get; set; }
        public string BLUK { get; set; }
        public string SAMT { get; set; }
        public int? N_TABAGHE { get; set; }
        public string VAHED { get; set; }
        public int? N_POSTALCODE { get; set; }
        public string ADDRESS { get; set; }
        public string DAFTARCODE { get; set; }
        public string DAFTERSABTNO { get; set; }
        public int? N_DAFTARSAFHE { get; set; }
        public int? DAFTARDATE { get; set; }
        public int? N_YEAR { get; set; }
        public string TASISAT { get; set; }
        public int? TABAGHETEDAD { get; set; }
        public int? OTAGHTEDAD { get; set; }
        public string OTHER { get; set; }
        public int? POSITIONID { get; set; }
        public string POSITION_TITLE { get; set; }
        public int? SOKONATID { get; set; }
        public string SOKONAT_TITLE { get; set; }
        public int? NAMAID { get; set; }
        public string NAMA_TITLE { get; set; }
        public int? KAFID { get; set; }
        public string KAF_TITLE { get; set; }
        public int? CABINETID { get; set; }
        public string CABINET_TITLE { get; set; }
        public int? SALON { get; set; }
        public int? BOKHARI { get; set; }
        public int? PACKAGE { get; set; }
        public int? MOTORKHANE { get; set; }
        public int? RADIATOR { get; set; }
        public int? FANCOIL { get; set; }
        public int? CHILLER { get; set; }
        public int? SPLIT { get; set; }
        public int? HAVASAZ { get; set; }
        public int? COOLER { get; set; }
        public int? COOLERGAS { get; set; }
        public int? GAZ { get; set; }
        public int? SHOMINE { get; set; }
        public int? IPHON { get; set; }
        public int? DORBIN { get; set; }
        public int? DOOD { get; set; }
        public int? BARGHZTERARI { get; set; }
        public int? PHONECENTER { get; set; }
        public int? BARGHSEFAZ { get; set; }
        public int? NORMAKHFI { get; set; }
        public int? DOZDGIR { get; set; }
        public int? TAMIRATCENTER { get; set; }
        public int? PELEKANEZTERARI { get; set; }
        public int? ATASHNESHANI { get; set; }
        public int? MOBLE { get; set; }
        public int? ESTAKHR { get; set; }
        public int? SONA { get; set; }
        public int? JAKOZI { get; set; }
        public int? MOSTAKHDEM { get; set; }
        public int? ASANSOR { get; set; }
        public int? BARBAR { get; set; }
        public int? RIMOT { get; set; }
        public int? ABTANK { get; set; }
        public int? SHOOTING { get; set; }
        public int? ZOBALESOZ { get; set; }
        public double? F_ARSE { get; set; }
        public int? WCIRANI { get; set; }
        public int? WCFARANGI { get; set; }
        public int? NAMAZKHANE { get; set; }
        public int? ABDARKHANE { get; set; }
        public int? ASHPAZKHANE { get; set; }
        public int? LABI { get; set; }
        public int? ANBARI { get; set; }
        public double? ANBARIM2 { get; set; }
        public int? PARKING { get; set; }
        public double? PARKINGM2 { get; set; }
        public double? BALCONM2 { get; set; }
        public string REMARK { get; set; }
        public int? VAHEDTEDAD { get; set; }
        public string HARARATI { get; set; }
        public string MECHANICI { get; set; }
        public string REFAHI { get; set; }
        public string ELECTRICI { get; set; }
        public string DOCS { get; set; }
        public string MELK_NAME { get; set; }
        public int? LAST_EXIT { get; set; }
        public int? LAST_RETURN { get; set; }
        public int? USERID { get; set; }
        public string USERSTR { get; set; }
    }
}
