using System;
using System.Collections.Generic;

#nullable disable

namespace amanatApi.Models
{
    public partial class VIEW_PAPER_FORM
    {
        public int PI_ID { get; set; }
        public double PI_QUANTITY { get; set; }
        public int? PI_SENDERID { get; set; }
        public string PI_SENDER_PID { get; set; }
        public string PI_SENDER_NAME { get; set; }
        public int? PI_SENDERLOCATIONID { get; set; }
        public string PI_SENDERLOCATION_TITLE { get; set; }
        public string PI_SENDERLOCATION_CODE { get; set; }
        public int? PI_SENDERROOTLOCATIONID { get; set; }
        public int? PI_QUANTITYUNIT { get; set; }
        public string PI_QUANTITYUNIT_STR { get; set; }
        public string PI_CONDITION_STR { get; set; }
        public int? PI_TASK_STR { get; set; }
        public string PI_DESCRIPTION { get; set; }
        public int? PI_DELIVERYDATE { get; set; }
        public int? STATUS { get; set; }
        public int? STATUS_BY { get; set; }
        public string STATUS_BY_NAME { get; set; }
        public string STATUS_BY_PIDS { get; set; }
        public int? STATUS_DATE { get; set; }
        public string STATUS_STR { get; set; }
        public int ASSET_ID { get; set; }
        public string ASSET_LABEL { get; set; }
        public string ASSET_NAME { get; set; }
        public string ASSET_SNBN { get; set; }
        public string ASSET_PN { get; set; }
        public string ASSET_MODEL { get; set; }
        public int? ASSET_BRAND { get; set; }
        public string ASSET_BRAND_STR { get; set; }
        public int ASSET_ASSETTYPE { get; set; }
        public string ASSET_LATINNAME { get; set; }
        public int? ASSET_COUNTRY { get; set; }
        public string ASSET_COUNTRY_STR { get; set; }
        public double? ASSET_VALUE { get; set; }
        public int? ASSET_CURRENCY { get; set; }
        public string ASSET_CURRENCY_STR { get; set; }
        public string ASSET_TRACKINGNO { get; set; }
        public int? ASSET_USAGE { get; set; }
        public string ASSET_SABTI_ASLI { get; set; }
        public string ASSET_SABTI_FAREI { get; set; }
        public string ASSET_VARAGHE_MALEKIAT { get; set; }
        public string ASSET_ENTEZAMI { get; set; }
        public string ASSET_MOTOR { get; set; }
        public string ASSET_SHASI { get; set; }
        public string ASSET_PHONE_NO { get; set; }
        public int P_ID { get; set; }
        public int P_NO { get; set; }
        public string P_FULLNO { get; set; }
        public int? P_PAPERDATE { get; set; }
        public int P_CREATEDATE { get; set; }
        public int? P_PAPEREXPDATE { get; set; }
        public int P_PAPERTYPE { get; set; }
        public string P_PAPERTYPE_STR { get; set; }
        public int P_ACTIVE { get; set; }
        public int? P_SEN_LOCATION { get; set; }
        public string P_SEN_LOCATION_TITLE { get; set; }
        public string P_SEN_LOCATION_CODE { get; set; }
        public int? P_SEN_USER { get; set; }
        public string P_SEN_USER_PID { get; set; }
        public string P_SEN_USER_NAME { get; set; }
        public int? P_REC_LOCATION { get; set; }
        public string P_REC_LOCATION_TITLE { get; set; }
        public string P_REC_LOCATION_CODE { get; set; }
        public int? P_REC_USER { get; set; }
        public string P_REC_USER_PID { get; set; }
        public string P_REC_USER_NAME { get; set; }
        public int? P_SEN_RES_LOCATION { get; set; }
        public string P_SEN_RES_LOCATION_TITLE { get; set; }
        public string P_SEN_RES_LOCATION_CODE { get; set; }
        public int? P_SEN_RES_USER { get; set; }
        public string P_SEN_RES_PID { get; set; }
        public string P_SEN_RES_NAME { get; set; }
        public int? P_SEN_AMIN_LOCATION { get; set; }
        public string P_SEN_AMIN_LOCATION_TITLE { get; set; }
        public string P_SEN_AMIN_LOCATION_CODE { get; set; }
        public int? P_SEN_AMIN_USER { get; set; }
        public string P_SEN_AMIN_PID { get; set; }
        public string P_SEN_AMIN_NAME { get; set; }
        public int? P_SEN_HAMIN_LOCATION { get; set; }
        public string P_SEN_HAMIN_LOCATION_TITLE { get; set; }
        public string P_SEN_HAMIN_LOCATION_CODE { get; set; }
        public int? P_SEN_HAMIN_USER { get; set; }
        public string P_SEN_HAMIN_PID { get; set; }
        public string P_SEN_HAMIN_NAME { get; set; }
        public int? P_REC_AMIN_LOCATION { get; set; }
        public string P_REC_AMIN_LOCATION_TITLE { get; set; }
        public string P_REC_AMIN_LOCATION_CODE { get; set; }
        public int? P_REC_AMIN_USER { get; set; }
        public string P_REC_AMIN_PID { get; set; }
        public string P_REC_AMIN_NAME { get; set; }
        public int? P_REC_HAMIN_LOCATION { get; set; }
        public int? P_REC_HAMIN_LOCATION_TITLE { get; set; }
        public int? P_REC_HAMIN_LOCATION_CODE { get; set; }
        public int? P_REC_HAMIN_USER { get; set; }
        public int? P_REC_HAMIN_PID { get; set; }
        public int? P_REC_HAMIN_NAME { get; set; }
        public string P_REC_RES_LOCATION_TITLE { get; set; }
        public string P_REC_RES_LOCATION_CODE { get; set; }
        public int? P_REC_RES_USER { get; set; }
        public string P_REC_RES_PID { get; set; }
        public string P_REC_RES_NAME { get; set; }
        public int P_CREATOR { get; set; }
        public string P_CREATOR_PID { get; set; }
        public string P_CREATOR_NAME { get; set; }
        public string P_LICENCE_NO { get; set; }
        public int? P_LICENCE_DATE { get; set; }
        public string P_LICENCE_CREATOR { get; set; }
        public string P_LICENCE_IMAGE_URL { get; set; }
        public int? P_RESERVEDFORUNIT { get; set; }
        public string P_RESERVEDFORUNIT_TITLE { get; set; }
        public string P_RESERVEDFORUNIT_CODE { get; set; }
        public int? P_DEADLINE { get; set; }
        public int? P_FKPRIORITY { get; set; }
        public string P_PRIORITY_STR { get; set; }
        public string P_AWB { get; set; }
        public string P_INVOICE_NO { get; set; }
        public double? P_INVOICE_PRICE { get; set; }
        public double? P_INVOICE_DISCOUNT { get; set; }
        public double? P_INVOICE_TAX { get; set; }
        public double? P_INVOICE_FINALPRICE { get; set; }
        public double? P_TRANSPORTCOST { get; set; }
        public double? P_COST_ADDITIVE { get; set; }
        public int? P_TRANSPORTDATE { get; set; }
        public string P_TRANSPORTER { get; set; }
        public int? P_DELIVERYDATE { get; set; }
        public int? P_INVOICE_DATE { get; set; }
        public string P_DESCRIPTION { get; set; }
        public double? P_COST_SUBTRACTIVE { get; set; }
        public int? P_RECEIPTDATE { get; set; }
        public int? P_INVOICE_CURRENCY { get; set; }
        public string P_LICENCE_DESCRIPTION { get; set; }
        public int? HOGHUGHI_USER { get; set; }
        public string HOGHUGHI_USER_PID { get; set; }
        public string HOGHUGHI_USER_NAME { get; set; }
        public int? HOGHUGHI_LOCATION { get; set; }
        public string HOGHUGHI_LOCATION_TITLE { get; set; }
        public string HOGHUGHI_LOCATION_CODE { get; set; }
        public int? KASR_COMPANY { get; set; }
        public string KASR_COMPANY_NAME { get; set; }
        public string KASR_RABETNAME { get; set; }
        public string KASR_PLAK_TAHVILI { get; set; }
        public double? KASR_SELL_VALUE { get; set; }
        public int? KASR_SELL_CURRENCY { get; set; }
        public string KASR_SELL_MOZAIEDE { get; set; }
        public int? KASR_SERGHAT_USERID { get; set; }
        public string KASR_SERGHAT_PID { get; set; }
        public string KASR_SERGHAT_NAME { get; set; }
        public double? KASR_SERGHAT_KARSHENASI { get; set; }
        public double? KASR_SERGHT_MANAVI { get; set; }
        public int? KASR_DEADLINE { get; set; }
        public int KASR_REMAIN { get; set; }
        public int? KASR_RETURN_DATE { get; set; }
        public int KASR_RETURNED { get; set; }
        public int? KASR_REASON { get; set; }
        public string KASR_REASON_STR { get; set; }
        public int? KASR_DATE { get; set; }
        public string SHOP { get; set; }
        public int? SHOPID { get; set; }
        public string SELLER { get; set; }
        public string SHOPADDRESS { get; set; }
        public string SHOPPHONE { get; set; }
        public int? MARJU_REASON { get; set; }
        public string MARJU_REASON_TITLE { get; set; }
        public int? RELATEDPAPER { get; set; }
    }
}
